### ISSUE TITLE
MQTT broker not available crash

### ISSUE THREAD

**Issue by TanasVlachopulos** [TanasVlachopulos/EspHub#4]
If MQTT broker is not available server crash immediately after start. Recomended solution: chatch exception paho mqtt broker.

```
Traceback (most recent call last):
  File "esphub.py", line 152, in <module>
    cli()
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "esphub.py", line 99, in start
    _collect_data(endless=False)
  File "esphub.py", line 65, in _collect_data
    Collector.DataCollector(conf.get('db', 'path'), 'config')
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/DeviceCom/DataCollector.py", line 21, in __init__
    self.mqtt = MessageHandler(conf.get('mqtt', 'ip'), conf.getint('mqtt', 'port'))
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/DeviceCom/MessageHandler.py", line 87, in __call__
    cls._instance[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/DeviceCom/MessageHandler.py", line 21, in __init__
    self._connect()
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/DeviceCom/MessageHandler.py", line 31, in _connect
    self.client.connect(self.broker_address, self.broker_port, self.keep_alive)
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 700, in connect
    return self.reconnect()
  File "/mnt/c/Users/Tanas/OneDrive/pracovni/SemProjekt/EspHubServer/venv/lib/python3.4/site-packages/paho/mqtt/client.py", line 854, in reconnect
    self._sock = sock
UnboundLocalError: local variable 'sock' referenced before assignment
```

**Comment by TanasVlachopulos** [comment]
I can't recreate this error message. Start EspHubServer with disabled MQTT broker, does not bring this error message.

I degradate this Issue to Potencial issue

**Comment by TanasVlachopulos** [comment]
Broker disconnection cause that MQTT collector thread died. 

Recomended actions, chach some exception and start reconnection loop.

**Comment by TanasVlachopulos** [comment]
duplicate with issue #37
